default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_purgatory_development

test:
  <<: *default
  database: rails_purgatory_test

production:
  <<: *default
  database: rails_purgatory_production
